spring:
 datasource:
   url: jdbc:sqlserver://sql2133.database.windows.net:1433;database=Springbootdatabase;user=Manoj21333@sql2133;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
   username: Manoj21333
   password: Manoj@123456
 jpa:  
   show-sql: true
   hibernate:
     ddl-auto: update
     dialect: org.hibernate.dialect.SQLServer2012Dialect
     
server:
  port: 9090